### ISSUE TITLE
wut is this?

### ISSUE THREAD

**Issue by wackypocket** [DarkholmeTenk/MMC-Companion#1]
just wondering what this is xD

**Comment by DarkholmeTenk** [comment]
A java program for maintaining up to date versions of my modpacks which you run before multimc :P Builds are on the jenkins if you want to give it a look :P

**Comment by wackypocket** [comment]
is your modpack public?

**Comment by DarkholmeTenk** [comment]
Yup, DarkBlast is the one that's most active atm; they can only really be downloaded with MMCCompanion (see http://darkcraft.io/install ) for vague instructions :P

**Comment by wackypocket** [comment]
whoa thats a ton of mods xD
edit: nvm i was looking a the wrong one :p

**Comment by wackypocket** [comment]
wtf! this is so cool! when is this version of the tardis mod gonna be released??

**Comment by wackypocket** [comment]
you can see the force field now? :D

**Comment by DarkholmeTenk** [comment]
Seeing the forcefield has always been a clientside config option, I just have it on because I like it and I accidentally put that as the config in the pack :3

**Comment by DarkholmeTenk** [comment]
There's a server at darkcraft.io if you want to join :)

**Comment by wackypocket** [comment]
lol and whats the link selection on the sonic?

**Comment by wackypocket** [comment]
oh cool!
